import {
  User,
  Workspace,
  WorkspaceMember,
  ReviewSystem,
  ReviewSystemVersion,
  ReviewRule,
  DistributionLink,
  Cohort,
  CohortMember,
  Subscription,
  SubscriptionPlan,
} from "@/lib/types/domain";

export const SEED_USERS: User[] = [
  {
    id: "usr_platform_admin",
    email: "admin@meai.internal",
    name: "System Administrator",
    role: "platform_admin",
    phone: "+254700000000",
    avatarUrl: "/avatars/admin.png",
    createdAt: "2026-07-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "usr_thorne_01",
    email: "aris.thorne@graduate.edu",
    name: "Dr. Aris Thorne",
    role: "workspace_owner",
    phone: "+254712345678",
    avatarUrl: "/avatars/thorne.png",
    createdAt: "2026-08-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "usr_marcus_fellow",
    email: "marcus.fellow@graduate.edu",
    name: "Dr. Marcus Fellow",
    role: "workspace_collaborator",
    phone: "+254733112233",
    avatarUrl: "/avatars/marcus.png",
    createdAt: "2026-08-10T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "usr_karen_legal",
    email: "karen.m@nairobilaw.co.ke",
    name: "Adv. Karen Mwangi",
    role: "workspace_owner",
    phone: "+254722998877",
    avatarUrl: "/avatars/karen.png",
    createdAt: "2026-08-15T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "usr_elena_student",
    email: "elena.rostova@cam.ac.uk",
    name: "Elena Rostova",
    role: "guest",
    phone: "+447911123456",
    avatarUrl: "/avatars/elena.png",
    createdAt: "2026-08-20T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export const SEED_WORKSPACES: Workspace[] = [
  {
    id: "ws_thorne_academic",
    name: "Graduate Systems Research Lab",
    slug: "systems-research-lab",
    ownerId: "usr_thorne_01",
    planTier: "PRO",
    subscriptionId: "sub_thorne_pro",
    retentionDays: 90,
    allowClientDataTraining: false,
    createdAt: "2026-08-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
  {
    id: "ws_karen_legal",
    name: "Mwangi & Partners Commercial Review",
    slug: "mwangi-commercial-law",
    ownerId: "usr_karen_legal",
    planTier: "PRO",
    subscriptionId: "sub_karen_pro",
    retentionDays: 30,
    allowClientDataTraining: false,
    createdAt: "2026-08-15T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export const SEED_WORKSPACE_MEMBERS: WorkspaceMember[] = [
  {
    id: "wsm_thorne_01",
    workspaceId: "ws_thorne_academic",
    userId: "usr_thorne_01",
    role: "owner",
    invitedAt: "2026-08-01T00:00:00.000Z",
    joinedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "wsm_marcus_fellow",
    workspaceId: "ws_thorne_academic",
    userId: "usr_marcus_fellow",
    role: "member",
    invitedAt: "2026-08-10T00:00:00.000Z",
    joinedAt: "2026-08-10T00:00:00.000Z",
  },
  {
    id: "wsm_karen_01",
    workspaceId: "ws_karen_legal",
    userId: "usr_karen_legal",
    role: "owner",
    invitedAt: "2026-08-15T00:00:00.000Z",
    joinedAt: "2026-08-15T00:00:00.000Z",
  },
];

export const SEED_PLANS: SubscriptionPlan[] = [
  {
    id: "plan_free",
    tier: "FREE",
    name: "Starter Professional",
    priceKesMonthly: 0,
    maxActiveReviewSystems: 1,
    maxMonthlyReviews: 15,
    cohortsEnabled: false,
    teamMembersEnabled: false,
    platformFeePercent: 10,
  },
  {
    id: "plan_pro",
    tier: "PRO",
    name: "Professional Practice",
    priceKesMonthly: 4900,
    maxActiveReviewSystems: 50,
    maxMonthlyReviews: 500,
    cohortsEnabled: true,
    teamMembersEnabled: true,
    platformFeePercent: 0,
  },
  {
    id: "plan_enterprise",
    tier: "ENTERPRISE",
    name: "Faculty & Firm Infrastructure",
    priceKesMonthly: 24000,
    maxActiveReviewSystems: 500,
    maxMonthlyReviews: 5000,
    cohortsEnabled: true,
    teamMembersEnabled: true,
    platformFeePercent: 0,
  },
];

export const SEED_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub_thorne_pro",
    workspaceId: "ws_thorne_academic",
    planTier: "PRO",
    status: "active",
    currentPeriodStart: "2026-09-01T00:00:00.000Z",
    currentPeriodEnd: "2026-10-01T00:00:00.000Z",
    cancelAtPeriodEnd: false,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
];

export const SEED_RULES_THORNE: ReviewRule[] = [
  {
    id: "rule_thorne_gap",
    ruleSystemVersionId: "ver_thesis_thorne_1_0_0",
    code: "RULE_GAP_01",
    title: "Unquantified Problem Statement Fluff",
    category: "Problem Formulation",
    description: "The problem statement must articulate a concrete, measurable empirical tension or performance bottleneck. Generic phrases like 'X has become increasingly important' without empirical stakes are rejected.",
    ruleType: "required",
    severity: "critical",
    applicableSection: "Chapter 1",
    evidenceRequirement: "required",
    requirement: "Must identify a specific and defensible research, practical, or empirical gap with baseline metrics within the first 3 paragraphs.",
    failureAction: "flag",
    recommendation: "Replace generic claims with exact failure boundaries: specify degraded throughput, latency percentiles, error rates, or unaddressed constraint spaces.",
    weight: 9,
    order: 1,
  },
  {
    id: "rule_thorne_baselines",
    ruleSystemVersionId: "ver_thesis_thorne_1_0_0",
    code: "RULE_BASE_02",
    title: "Missing Threat to External Validity & Baselines",
    category: "Methodology",
    description: "Methodology must define both standard state-of-the-art baselines and explicit threats to external validity.",
    ruleType: "required",
    severity: "critical",
    applicableSection: "Chapter 3",
    evidenceRequirement: "required",
    requirement: "Benchmark against at least two standard state-of-the-art baselines under identical distribution constraints.",
    failureAction: "flag",
    recommendation: "Explicitly identify comparative baselines (e.g. BM25, Lucene, standard HNSW) and state how experimental variance is controlled.",
    weight: 8,
    order: 2,
  },
  {
    id: "rule_thorne_lineage",
    ruleSystemVersionId: "ver_thesis_thorne_1_0_0",
    code: "RULE_LIT_03",
    title: "Anachronistic or Unconnected Literature Citation",
    category: "Literature Review",
    description: "Literature review must not be a chronological list; it must establish an intellectual lineage terminating in the specific gap this research fills.",
    ruleType: "relationship",
    severity: "high",
    applicableSection: "Chapter 2",
    evidenceRequirement: "required",
    requirement: "Every referenced author cluster must explicitly state what boundary condition they failed to resolve.",
    failureAction: "warn",
    recommendation: "Group citations by technical lineage rather than author chronologies. For each prior work, state the exact limitation that creates the aperture for your study.",
    weight: 7,
    order: 3,
  },
  {
    id: "rule_thorne_orphan_figures",
    ruleSystemVersionId: "ver_thesis_thorne_1_0_0",
    code: "RULE_FIG_04",
    title: "Orphan Figures & Tables without In-Text Discussion",
    category: "Structure & Evidence",
    description: "No diagram, figure, or table may exist without an explicit in-text interpretation explaining the unexpected or salient anomaly in the data.",
    ruleType: "structural",
    severity: "medium",
    applicableSection: "All",
    evidenceRequirement: "required",
    requirement: "All Figures and Tables must be explicitly cited, parsed, and interpreted in the adjacent prose.",
    failureAction: "warn",
    recommendation: "Add explanatory prose linking each figure to the deductive hypothesis it supports or disproves.",
    weight: 5,
    order: 4,
  },
  {
    id: "rule_thorne_causal",
    ruleSystemVersionId: "ver_thesis_thorne_1_0_0",
    code: "RULE_INTEG_05",
    title: "Unsupported Causal Assertions",
    category: "Academic Rigor",
    description: "Phrases asserting causality ('This proves that X leads to Y') without controlled ablation or statistical significance (p < 0.05) are disallowed.",
    ruleType: "evidence-based",
    severity: "critical",
    applicableSection: "All",
    evidenceRequirement: "required",
    requirement: "Must use qualified language ('suggests correlation', 'within experimental bounds') unless formal statistical significance test is reported.",
    failureAction: "flag",
    recommendation: "Soft-claim causal language to correlation or report standard deviation and p-values for all comparative measurements.",
    weight: 8,
    order: 5,
  },
];

export const SEED_REVIEW_SYSTEM_VERSIONS: ReviewSystemVersion[] = [
  {
    id: "ver_thesis_thorne_1_0_0",
    reviewSystemId: "revsys_thesis_thorne",
    versionNumber: "1.0.0",
    changelog: "Initial production release of Dr. Thorne's Dissertation Diagnostic Methodology.",
    rules: SEED_RULES_THORNE,
    examples: [
      {
        id: "ex_gap_good",
        ruleId: "rule_thorne_gap",
        type: "good",
        content: "Existing vector indexing strategies degrade from 98% recall to 64% when query dimensionality exceeds D=1536 under 100ms latency budgets.",
        annotation: "Clear quantified empirical baseline with specific failure threshold.",
      },
      {
        id: "ex_gap_bad",
        ruleId: "rule_thorne_gap",
        type: "bad",
        content: "In modern artificial intelligence, vector search has become very important for retrieving accurate results for users.",
        annotation: "Vague generic fluff with zero empirical stakes or baseline measurements.",
      },
    ],
    settings: {
      supportedFileTypes: ["pdf", "docx", "txt", "md"],
      maxFileSizeMb: 25,
      autoProcessOnPayment: true,
      scoringScale: "percentage",
      passingScore: 75,
      humanOversightRequired: false,
    },
    isPublished: true,
    publishedAt: "2026-08-10T00:00:00.000Z",
    publishedBy: "usr_thorne_01",
    isImmutable: true,
    createdAt: "2026-08-01T00:00:00.000Z",
  },
];

export const SEED_REVIEW_SYSTEMS: ReviewSystem[] = [
  {
    id: "revsys_thesis_thorne",
    workspaceId: "ws_thorne_academic",
    name: "Doctoral Dissertation Chapter 1–3 Diagnostic",
    slug: "dr-thorne-dissertation-diagnostic",
    discipline: "Computer Science & Systems Engineering",
    audience: "Doctoral Candidates & Master's Researchers",
    description: "Structured evaluation of Problem Statement specificity, Baseline benchmarking rigor, Literature lineage, and Causal claim integrity before defense committee submission.",
    evaluationScope: "Chapters 1 (Introduction & Problem), Chapter 2 (Literature Lineage), Chapter 3 (Methodology & Validity).",
    ignoredScope: "Formatting margins, acknowledgements, grammar style conventions, font choices.",
    priceKes: 500,
    currentVersionId: "ver_thesis_thorne_1_0_0",
    status: "published",
    createdAt: "2026-08-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export const SEED_DISTRIBUTION_LINKS: DistributionLink[] = [
  {
    id: "link_thorne_public",
    reviewSystemId: "revsys_thesis_thorne",
    reviewSystemVersionId: "ver_thesis_thorne_1_0_0",
    token: "thorne-phd-review-2026",
    name: "Public Thesis Submission Link",
    accessMode: "PAID",
    priceKes: 500,
    usageLimit: 500,
    usageCount: 18,
    isActive: true,
    createdAt: "2026-08-10T00:00:00.000Z",
  },
  {
    id: "link_thorne_cohort_cs2026",
    reviewSystemId: "revsys_thesis_thorne",
    reviewSystemVersionId: "ver_thesis_thorne_1_0_0",
    token: "cs-postgrad-cohort-2026",
    name: "CS Postgraduate Cohort 2026 (Included)",
    accessMode: "INCLUDED",
    priceKes: 0,
    cohortId: "cohort_cs_postgrad_2026",
    usageLimit: 50,
    usageCount: 12,
    isActive: true,
    createdAt: "2026-08-12T00:00:00.000Z",
  },
];

export const SEED_COHORTS: Cohort[] = [
  {
    id: "cohort_cs_postgrad_2026",
    workspaceId: "ws_thorne_academic",
    reviewSystemId: "revsys_thesis_thorne",
    name: "CS Postgraduate Final Year Projects 2026",
    description: "Master of Science in Distributed Systems & AI Candidates - Fall 2026 Defense Milestone.",
    startDate: "2026-08-15T00:00:00.000Z",
    endDate: "2026-11-30T00:00:00.000Z",
    distributionLinkId: "link_thorne_cohort_cs2026",
    createdAt: "2026-08-12T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
  },
];

export const SEED_COHORT_MEMBERS: CohortMember[] = [
  {
    id: "cm_01",
    cohortId: "cohort_cs_postgrad_2026",
    studentIdentifier: "CS/MSC/2026/014",
    name: "Dennis Kiprop",
    email: "dkiprop@student.uonbi.ac.ke",
    submissionsCount: 2,
    latestScore: 88,
    status: "completed",
  },
  {
    id: "cm_02",
    cohortId: "cohort_cs_postgrad_2026",
    studentIdentifier: "CS/MSC/2026/029",
    name: "Amina Mohamed",
    email: "amohamed@student.uonbi.ac.ke",
    submissionsCount: 1,
    latestScore: 54,
    status: "at_risk",
  },
  {
    id: "cm_03",
    cohortId: "cohort_cs_postgrad_2026",
    studentIdentifier: "CS/MSC/2026/033",
    name: "Brian Otieno",
    email: "botieno@student.uonbi.ac.ke",
    submissionsCount: 1,
    latestScore: 76,
    status: "active",
  },
];
